<p><b>[DEBUG]</b>&nbsp;Text received successfully.</p><p><b>[DEBUG]</b>&nbsp;Assertion polling statistics:<br>First element asserted in: 0.018980979919433594 seconds<br>Total tries: 47<br>Elapsed time in retries 1.0290541648864746 seconds</p><p><b>[DEBUG]</b>&nbsp;Using /Users/eder.angelo/Documents/Projeto/teste/desafio_bees/web/logs/I_must_complete_the_purchase_successfully_FAILURE_SCREENSHOT_{index} to take screenshot.</p><p><b>[DEBUG]</b>&nbsp;Screenshot succesfully captured to: /Users/eder.angelo/Documents/Projeto/teste/desafio_bees/web/logs/I_must_complete_the_purchase_successfully_FAILURE_SCREENSHOT_1.png</p><p><b>[INFO]</b>&nbsp;</td></tr><tr><td colspan="3"><a href="I_must_complete_the_purchase_successfully_FAILURE_SCREENSHOT_1.png"><img src="I_must_complete_the_purchase_successfully_FAILURE_SCREENSHOT_1.png" width="800px"></a></p><p style="color: red"><b>[FAIL]</b>&nbsp;Text 'CHECKOUT: YOUR INFORMATION' (str) should be 'tessss ##CHECKOUT: YOUR INFORMATION' (str)</p><p><b>[DEBUG]</b>&nbsp;Traceback (most recent call last):<br>  File "/usr/local/lib/python3.9/site-packages/Browser/browser.py", line 882, in run_keyword<br>    raise e<br>  File "/usr/local/lib/python3.9/site-packages/Browser/browser.py", line 872, in run_keyword<br>    return DynamicCore.run_keyword(self, name, args, kwargs)<br>  File "/usr/local/lib/python3.9/site-packages/robotlibcore.py", line 94, in run_keyword<br>    return self.keywords[name](*args, **(kwargs or {}))<br>  File "/usr/local/lib/python3.9/site-packages/Browser/assertion_engine.py", line 41, in with_assertion_polling<br>    raise e<br>  File "/usr/local/lib/python3.9/site-packages/Browser/assertion_engine.py", line 34, in with_assertion_polling<br>    return wrapped(*args, **kwargs)<br>  File "/usr/local/lib/python3.9/site-packages/Browser/keywords/getters.py", line 214, in get_text<br>    return verify_assertion(<br>  File "/usr/local/lib/python3.9/site-packages/assertionengine/assertion_engine.py", line 191, in verify_assertion<br>    raise AssertionError(error_msg)</p>